export const QUERY_KEY = {
  GOALS: 'GOALS',
  MONTHLY_TODOS: 'MONTHLY_TODOS',
  DAILY_TODOS: 'DAILY_TODOS',
  GOAL_TODOS: 'GOAL_TODOS',
  GOAL_NOTES: 'GOAL_NOTES',
  GRASS: 'GRASS',
  TODO: 'TODO',
  GOAL: 'GOAL',
  NOTE: 'NOTE',
  TODO_BASKET: 'TODO_BASKET',
} as const;
